#!/bin/sh
# @(#) $Header: bihourly,v 1.1 96/11/07 17:39:23 leres Exp $ (LBL)
#
#  bihourly arpwatch job
#
PATH=$PATH:/usr/local/sbin
export PATH
#
cd /usr/operator/arpwatch
#
list=`cat list`
cname=`cat cname`
errs=/tmp/bihourly.$$
#
alist=""
for r in $list; do \
	./arpfetch $r $cname > $r 2> $errs
	if test -s $errs; then
		echo "arpfetch $r failed:"
		sed -e 's/^/    /' $errs
		continue
	fi
	alist="$alist $r"
done
#
rm -f $errs
arpsnmp $alist
#
exit 0
