.TH MASSAGEVENDOR 8
.SH NAME
massagevendor \- convert the ethernet vendor codes master list to arpwatch format
.SH SYNOPSIS
.na
massagevendor
.I vendorfile
.SH "DESCRIPTION"
.B massagevendor
is a program that converts a text file containing ethernet vendor codes
into a format suitable for use by
.B arpwatch(8)
and
.B arpsnmp(8).
The input
.I vendorfile
is a master text file containing vendor codes. The output
is sent to
.I stdout.
Each line of the
.I vendorfile
is expected to have a six digit hexadecimal vendor code
followed by spaces followed by the name of the manufacturer.
.LP
All ethernet devices have a unique identifier which
includes a vendor code specifying the manufacturer of the
device. In normal operation
.B arpwatch(8)
and
.B arpsnmp(8)
use the file
.I ethercodes.dat
to report this vendor code.
.B massagevendor
is used to generate the
.I ethercodes.dat
file from text files containing these vendor codes.
.LP
Locations where an ethernet vendor codes master text file
can be obtained are given below.
.SH FILES
.na
.nh
.nf
/usr/share/arpwatch - default location of the ethernet vendor list
ethercodes.dat - file containing the list of ethernet vendor codes
.ad
.hy
.fi
.SH "SEE ALSO"
.na
.nh
.BR arpwatch(8),
.BR arpsnmp(8)
.ad
.hy
.SH NOTES
Sources for ethernet vendor codes seen in the wild are
.LP
.na
.nh
.nf
.RS
.I http://map-ne.com/Ethernet/vendor.html
.I ftp://ftp.cavebear.com/pub/Ethernet.txt
.I http://www.cavebear.com/CaveBear/Ethernet/vendor.html
.RE
.ad
.hy
.LP
Useful for comparison or completeness are the
ethernet vendor codes as assigned
by the IEEE which can be found at
.LP
.RS
.I http://standards.ieee.org/regauth/oui/oui.txt
.RE
.SH BUGS
Please send bug reports to arpwatch@ee.lbl.gov.
.SH AUTHORS
Craig Leres of the
Lawrence Berkeley National Laboratory Network Research Group,
University of California, Berkeley, CA.
.LP
The current version is available via anonymous ftp:
.LP
.RS
.I ftp://ftp.ee.lbl.gov/arpwatch.tar.gz
.RE
.LP
This manual page was contributed by Hugo Graumann.
