#!/bin/sh
# arpwatch.preinst: v0.02 2001/11/24 KELEMEN Peter <fuji@debian.org>

set -e

#DEBHELPER#

NAME=arpwatch
DBDIR=/var/lib/$NAME
DBFILE=arp.dat
BACKUPDIR=/var/backups
BACKUPNAME=$NAME.dbbackup

[ -d $DBDIR ] || exit 0
[ -f $DBDIR/$DBFILE ] || touch $DBDIR/$DBFILE
[ -d $BACKUPDIR ] || { 
	echo "$NAME: $BACKUPDIR does not exist, ARP database(s) not saved.";
	exit 0
}

echo "$NAME: Saving collected ARP database(s)."
cp -rp $DBDIR $BACKUPDIR/$BACKUPNAME

# End of file.
