#!/bin/sh
# KELEMEN Peter <fuji@debian.org>
# postinst maintainer script for arpwatch

set -e

# Attempt to save ethernet/ip database from 2.1a4-1.

DBFILE=arp.dat
OLDDIR=/var/run/arpwatch
NEWDIR=/var/lib/arpwatch

if [ -s $OLDDIR/$DBFILE ]; then
	cp $OLDDIR/$DBFILE $NEWDIR
fi

# If arp.dat doesn't exist, it creates an empty one.  This way upgrades are
# not going to destroy already collected database content.
touch /var/lib/arpwatch/arp.dat

#DEBHELPER#
